########################################################################################
# https://developer.hashicorp.com/terraform/tutorials/configuration-language/move-config

# OCM-3565
# Network interfaces moved from node module to onefs module.
#
# GENERATED BY SCRIPT in codegen/


moved {
  from = module.bootstrap_nodes[0].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[0]
}

moved {
  from = module.bootstrap_nodes[0].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[0]
}

moved {
  from = module.bootstrap_nodes[0].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[0]
}

moved {
  from = module.additional_nodes[0].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[1]
}

moved {
  from = module.additional_nodes[0].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[1]
}

moved {
  from = module.additional_nodes[0].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[1]
}


moved {
  from = module.additional_nodes[1].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[2]
}

moved {
  from = module.additional_nodes[1].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[2]
}

moved {
  from = module.additional_nodes[1].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[2]
}


moved {
  from = module.additional_nodes[2].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[3]
}

moved {
  from = module.additional_nodes[2].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[3]
}

moved {
  from = module.additional_nodes[2].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[3]
}


moved {
  from = module.additional_nodes[3].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[4]
}

moved {
  from = module.additional_nodes[3].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[4]
}

moved {
  from = module.additional_nodes[3].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[4]
}


moved {
  from = module.additional_nodes[4].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[5]
}

moved {
  from = module.additional_nodes[4].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[5]
}

moved {
  from = module.additional_nodes[4].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[5]
}


moved {
  from = module.additional_nodes[5].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[6]
}

moved {
  from = module.additional_nodes[5].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[6]
}

moved {
  from = module.additional_nodes[5].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[6]
}


moved {
  from = module.additional_nodes[6].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[7]
}

moved {
  from = module.additional_nodes[6].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[7]
}

moved {
  from = module.additional_nodes[6].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[7]
}


moved {
  from = module.additional_nodes[7].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[8]
}

moved {
  from = module.additional_nodes[7].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[8]
}

moved {
  from = module.additional_nodes[7].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[8]
}


moved {
  from = module.additional_nodes[8].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[9]
}

moved {
  from = module.additional_nodes[8].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[9]
}

moved {
  from = module.additional_nodes[8].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[9]
}


moved {
  from = module.additional_nodes[9].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[10]
}

moved {
  from = module.additional_nodes[9].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[10]
}

moved {
  from = module.additional_nodes[9].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[10]
}


moved {
  from = module.additional_nodes[10].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[11]
}

moved {
  from = module.additional_nodes[10].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[11]
}

moved {
  from = module.additional_nodes[10].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[11]
}


moved {
  from = module.additional_nodes[11].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[12]
}

moved {
  from = module.additional_nodes[11].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[12]
}

moved {
  from = module.additional_nodes[11].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[12]
}


moved {
  from = module.additional_nodes[12].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[13]
}

moved {
  from = module.additional_nodes[12].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[13]
}

moved {
  from = module.additional_nodes[12].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[13]
}


moved {
  from = module.additional_nodes[13].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[14]
}

moved {
  from = module.additional_nodes[13].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[14]
}

moved {
  from = module.additional_nodes[13].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[14]
}


moved {
  from = module.additional_nodes[14].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[15]
}

moved {
  from = module.additional_nodes[14].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[15]
}

moved {
  from = module.additional_nodes[14].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[15]
}


moved {
  from = module.additional_nodes[15].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[16]
}

moved {
  from = module.additional_nodes[15].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[16]
}

moved {
  from = module.additional_nodes[15].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[16]
}


moved {
  from = module.additional_nodes[16].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[17]
}

moved {
  from = module.additional_nodes[16].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[17]
}

moved {
  from = module.additional_nodes[16].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[17]
}


moved {
  from = module.additional_nodes[17].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[18]
}

moved {
  from = module.additional_nodes[17].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[18]
}

moved {
  from = module.additional_nodes[17].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[18]
}


moved {
  from = module.additional_nodes[18].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[19]
}

moved {
  from = module.additional_nodes[18].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[19]
}

moved {
  from = module.additional_nodes[18].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[19]
}


moved {
  from = module.additional_nodes[19].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[20]
}

moved {
  from = module.additional_nodes[19].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[20]
}

moved {
  from = module.additional_nodes[19].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[20]
}


moved {
  from = module.additional_nodes[20].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[21]
}

moved {
  from = module.additional_nodes[20].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[21]
}

moved {
  from = module.additional_nodes[20].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[21]
}


moved {
  from = module.additional_nodes[21].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[22]
}

moved {
  from = module.additional_nodes[21].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[22]
}

moved {
  from = module.additional_nodes[21].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[22]
}


moved {
  from = module.additional_nodes[22].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[23]
}

moved {
  from = module.additional_nodes[22].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[23]
}

moved {
  from = module.additional_nodes[22].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[23]
}


moved {
  from = module.additional_nodes[23].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[24]
}

moved {
  from = module.additional_nodes[23].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[24]
}

moved {
  from = module.additional_nodes[23].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[24]
}


moved {
  from = module.additional_nodes[24].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[25]
}

moved {
  from = module.additional_nodes[24].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[25]
}

moved {
  from = module.additional_nodes[24].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[25]
}


moved {
  from = module.additional_nodes[25].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[26]
}

moved {
  from = module.additional_nodes[25].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[26]
}

moved {
  from = module.additional_nodes[25].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[26]
}


moved {
  from = module.additional_nodes[26].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[27]
}

moved {
  from = module.additional_nodes[26].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[27]
}

moved {
  from = module.additional_nodes[26].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[27]
}


moved {
  from = module.additional_nodes[27].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[28]
}

moved {
  from = module.additional_nodes[27].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[28]
}

moved {
  from = module.additional_nodes[27].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[28]
}


moved {
  from = module.additional_nodes[28].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[29]
}

moved {
  from = module.additional_nodes[28].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[29]
}

moved {
  from = module.additional_nodes[28].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[29]
}


moved {
  from = module.additional_nodes[29].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[30]
}

moved {
  from = module.additional_nodes[29].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[30]
}

moved {
  from = module.additional_nodes[29].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[30]
}


moved {
  from = module.additional_nodes[30].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[31]
}

moved {
  from = module.additional_nodes[30].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[31]
}

moved {
  from = module.additional_nodes[30].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[31]
}


moved {
  from = module.additional_nodes[31].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[32]
}

moved {
  from = module.additional_nodes[31].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[32]
}

moved {
  from = module.additional_nodes[31].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[32]
}


moved {
  from = module.additional_nodes[32].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[33]
}

moved {
  from = module.additional_nodes[32].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[33]
}

moved {
  from = module.additional_nodes[32].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[33]
}


moved {
  from = module.additional_nodes[33].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[34]
}

moved {
  from = module.additional_nodes[33].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[34]
}

moved {
  from = module.additional_nodes[33].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[34]
}


moved {
  from = module.additional_nodes[34].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[35]
}

moved {
  from = module.additional_nodes[34].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[35]
}

moved {
  from = module.additional_nodes[34].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[35]
}


moved {
  from = module.additional_nodes[35].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[36]
}

moved {
  from = module.additional_nodes[35].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[36]
}

moved {
  from = module.additional_nodes[35].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[36]
}


moved {
  from = module.additional_nodes[36].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[37]
}

moved {
  from = module.additional_nodes[36].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[37]
}

moved {
  from = module.additional_nodes[36].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[37]
}


moved {
  from = module.additional_nodes[37].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[38]
}

moved {
  from = module.additional_nodes[37].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[38]
}

moved {
  from = module.additional_nodes[37].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[38]
}


moved {
  from = module.additional_nodes[38].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[39]
}

moved {
  from = module.additional_nodes[38].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[39]
}

moved {
  from = module.additional_nodes[38].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[39]
}


moved {
  from = module.additional_nodes[39].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[40]
}

moved {
  from = module.additional_nodes[39].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[40]
}

moved {
  from = module.additional_nodes[39].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[40]
}


moved {
  from = module.additional_nodes[40].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[41]
}

moved {
  from = module.additional_nodes[40].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[41]
}

moved {
  from = module.additional_nodes[40].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[41]
}


moved {
  from = module.additional_nodes[41].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[42]
}

moved {
  from = module.additional_nodes[41].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[42]
}

moved {
  from = module.additional_nodes[41].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[42]
}


moved {
  from = module.additional_nodes[42].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[43]
}

moved {
  from = module.additional_nodes[42].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[43]
}

moved {
  from = module.additional_nodes[42].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[43]
}


moved {
  from = module.additional_nodes[43].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[44]
}

moved {
  from = module.additional_nodes[43].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[44]
}

moved {
  from = module.additional_nodes[43].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[44]
}


moved {
  from = module.additional_nodes[44].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[45]
}

moved {
  from = module.additional_nodes[44].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[45]
}

moved {
  from = module.additional_nodes[44].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[45]
}


moved {
  from = module.additional_nodes[45].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[46]
}

moved {
  from = module.additional_nodes[45].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[46]
}

moved {
  from = module.additional_nodes[45].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[46]
}


moved {
  from = module.additional_nodes[46].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[47]
}

moved {
  from = module.additional_nodes[46].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[47]
}

moved {
  from = module.additional_nodes[46].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[47]
}


moved {
  from = module.additional_nodes[47].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[48]
}

moved {
  from = module.additional_nodes[47].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[48]
}

moved {
  from = module.additional_nodes[47].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[48]
}


moved {
  from = module.additional_nodes[48].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[49]
}

moved {
  from = module.additional_nodes[48].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[49]
}

moved {
  from = module.additional_nodes[48].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[49]
}


moved {
  from = module.additional_nodes[49].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[50]
}

moved {
  from = module.additional_nodes[49].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[50]
}

moved {
  from = module.additional_nodes[49].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[50]
}


moved {
  from = module.additional_nodes[50].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[51]
}

moved {
  from = module.additional_nodes[50].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[51]
}

moved {
  from = module.additional_nodes[50].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[51]
}


moved {
  from = module.additional_nodes[51].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[52]
}

moved {
  from = module.additional_nodes[51].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[52]
}

moved {
  from = module.additional_nodes[51].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[52]
}


moved {
  from = module.additional_nodes[52].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[53]
}

moved {
  from = module.additional_nodes[52].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[53]
}

moved {
  from = module.additional_nodes[52].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[53]
}


moved {
  from = module.additional_nodes[53].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[54]
}

moved {
  from = module.additional_nodes[53].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[54]
}

moved {
  from = module.additional_nodes[53].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[54]
}


moved {
  from = module.additional_nodes[54].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[55]
}

moved {
  from = module.additional_nodes[54].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[55]
}

moved {
  from = module.additional_nodes[54].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[55]
}


moved {
  from = module.additional_nodes[55].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[56]
}

moved {
  from = module.additional_nodes[55].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[56]
}

moved {
  from = module.additional_nodes[55].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[56]
}


moved {
  from = module.additional_nodes[56].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[57]
}

moved {
  from = module.additional_nodes[56].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[57]
}

moved {
  from = module.additional_nodes[56].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[57]
}


moved {
  from = module.additional_nodes[57].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[58]
}

moved {
  from = module.additional_nodes[57].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[58]
}

moved {
  from = module.additional_nodes[57].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[58]
}


moved {
  from = module.additional_nodes[58].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[59]
}

moved {
  from = module.additional_nodes[58].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[59]
}

moved {
  from = module.additional_nodes[58].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[59]
}


moved {
  from = module.additional_nodes[59].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[60]
}

moved {
  from = module.additional_nodes[59].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[60]
}

moved {
  from = module.additional_nodes[59].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[60]
}


moved {
  from = module.additional_nodes[60].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[61]
}

moved {
  from = module.additional_nodes[60].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[61]
}

moved {
  from = module.additional_nodes[60].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[61]
}


moved {
  from = module.additional_nodes[61].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[62]
}

moved {
  from = module.additional_nodes[61].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[62]
}

moved {
  from = module.additional_nodes[61].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[62]
}


moved {
  from = module.additional_nodes[62].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[63]
}

moved {
  from = module.additional_nodes[62].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[63]
}

moved {
  from = module.additional_nodes[62].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[63]
}


moved {
  from = module.additional_nodes[63].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[64]
}

moved {
  from = module.additional_nodes[63].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[64]
}

moved {
  from = module.additional_nodes[63].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[64]
}


moved {
  from = module.additional_nodes[64].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[65]
}

moved {
  from = module.additional_nodes[64].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[65]
}

moved {
  from = module.additional_nodes[64].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[65]
}


moved {
  from = module.additional_nodes[65].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[66]
}

moved {
  from = module.additional_nodes[65].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[66]
}

moved {
  from = module.additional_nodes[65].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[66]
}


moved {
  from = module.additional_nodes[66].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[67]
}

moved {
  from = module.additional_nodes[66].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[67]
}

moved {
  from = module.additional_nodes[66].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[67]
}


moved {
  from = module.additional_nodes[67].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[68]
}

moved {
  from = module.additional_nodes[67].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[68]
}

moved {
  from = module.additional_nodes[67].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[68]
}


moved {
  from = module.additional_nodes[68].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[69]
}

moved {
  from = module.additional_nodes[68].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[69]
}

moved {
  from = module.additional_nodes[68].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[69]
}


moved {
  from = module.additional_nodes[69].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[70]
}

moved {
  from = module.additional_nodes[69].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[70]
}

moved {
  from = module.additional_nodes[69].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[70]
}


moved {
  from = module.additional_nodes[70].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[71]
}

moved {
  from = module.additional_nodes[70].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[71]
}

moved {
  from = module.additional_nodes[70].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[71]
}


moved {
  from = module.additional_nodes[71].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[72]
}

moved {
  from = module.additional_nodes[71].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[72]
}

moved {
  from = module.additional_nodes[71].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[72]
}


moved {
  from = module.additional_nodes[72].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[73]
}

moved {
  from = module.additional_nodes[72].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[73]
}

moved {
  from = module.additional_nodes[72].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[73]
}


moved {
  from = module.additional_nodes[73].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[74]
}

moved {
  from = module.additional_nodes[73].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[74]
}

moved {
  from = module.additional_nodes[73].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[74]
}


moved {
  from = module.additional_nodes[74].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[75]
}

moved {
  from = module.additional_nodes[74].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[75]
}

moved {
  from = module.additional_nodes[74].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[75]
}


moved {
  from = module.additional_nodes[75].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[76]
}

moved {
  from = module.additional_nodes[75].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[76]
}

moved {
  from = module.additional_nodes[75].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[76]
}


moved {
  from = module.additional_nodes[76].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[77]
}

moved {
  from = module.additional_nodes[76].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[77]
}

moved {
  from = module.additional_nodes[76].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[77]
}


moved {
  from = module.additional_nodes[77].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[78]
}

moved {
  from = module.additional_nodes[77].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[78]
}

moved {
  from = module.additional_nodes[77].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[78]
}


moved {
  from = module.additional_nodes[78].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[79]
}

moved {
  from = module.additional_nodes[78].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[79]
}

moved {
  from = module.additional_nodes[78].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[79]
}


moved {
  from = module.additional_nodes[79].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[80]
}

moved {
  from = module.additional_nodes[79].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[80]
}

moved {
  from = module.additional_nodes[79].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[80]
}


moved {
  from = module.additional_nodes[80].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[81]
}

moved {
  from = module.additional_nodes[80].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[81]
}

moved {
  from = module.additional_nodes[80].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[81]
}


moved {
  from = module.additional_nodes[81].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[82]
}

moved {
  from = module.additional_nodes[81].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[82]
}

moved {
  from = module.additional_nodes[81].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[82]
}


moved {
  from = module.additional_nodes[82].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[83]
}

moved {
  from = module.additional_nodes[82].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[83]
}

moved {
  from = module.additional_nodes[82].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[83]
}


moved {
  from = module.additional_nodes[83].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[84]
}

moved {
  from = module.additional_nodes[83].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[84]
}

moved {
  from = module.additional_nodes[83].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[84]
}


moved {
  from = module.additional_nodes[84].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[85]
}

moved {
  from = module.additional_nodes[84].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[85]
}

moved {
  from = module.additional_nodes[84].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[85]
}


moved {
  from = module.additional_nodes[85].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[86]
}

moved {
  from = module.additional_nodes[85].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[86]
}

moved {
  from = module.additional_nodes[85].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[86]
}


moved {
  from = module.additional_nodes[86].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[87]
}

moved {
  from = module.additional_nodes[86].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[87]
}

moved {
  from = module.additional_nodes[86].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[87]
}


moved {
  from = module.additional_nodes[87].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[88]
}

moved {
  from = module.additional_nodes[87].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[88]
}

moved {
  from = module.additional_nodes[87].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[88]
}


moved {
  from = module.additional_nodes[88].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[89]
}

moved {
  from = module.additional_nodes[88].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[89]
}

moved {
  from = module.additional_nodes[88].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[89]
}


moved {
  from = module.additional_nodes[89].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[90]
}

moved {
  from = module.additional_nodes[89].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[90]
}

moved {
  from = module.additional_nodes[89].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[90]
}


moved {
  from = module.additional_nodes[90].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[91]
}

moved {
  from = module.additional_nodes[90].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[91]
}

moved {
  from = module.additional_nodes[90].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[91]
}


moved {
  from = module.additional_nodes[91].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[92]
}

moved {
  from = module.additional_nodes[91].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[92]
}

moved {
  from = module.additional_nodes[91].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[92]
}


moved {
  from = module.additional_nodes[92].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[93]
}

moved {
  from = module.additional_nodes[92].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[93]
}

moved {
  from = module.additional_nodes[92].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[93]
}


moved {
  from = module.additional_nodes[93].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[94]
}

moved {
  from = module.additional_nodes[93].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[94]
}

moved {
  from = module.additional_nodes[93].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[94]
}


moved {
  from = module.additional_nodes[94].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[95]
}

moved {
  from = module.additional_nodes[94].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[95]
}

moved {
  from = module.additional_nodes[94].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[95]
}


moved {
  from = module.additional_nodes[95].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[96]
}

moved {
  from = module.additional_nodes[95].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[96]
}

moved {
  from = module.additional_nodes[95].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[96]
}


moved {
  from = module.additional_nodes[96].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[97]
}

moved {
  from = module.additional_nodes[96].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[97]
}

moved {
  from = module.additional_nodes[96].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[97]
}


moved {
  from = module.additional_nodes[97].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[98]
}

moved {
  from = module.additional_nodes[97].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[98]
}

moved {
  from = module.additional_nodes[97].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[98]
}


moved {
  from = module.additional_nodes[98].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[99]
}

moved {
  from = module.additional_nodes[98].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[99]
}

moved {
  from = module.additional_nodes[98].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[99]
}


moved {
  from = module.additional_nodes[99].aws_network_interface.external_interface
  to   = aws_network_interface.external_interface[100]
}

moved {
  from = module.additional_nodes[99].aws_network_interface.mgmt_interface
  to   = aws_network_interface.mgmt_interface[100]
}

moved {
  from = module.additional_nodes[99].aws_network_interface.internal_interface
  to   = aws_network_interface.internal_interface[100]
}

