########################################################################################
# https://developer.hashicorp.com/terraform/tutorials/configuration-language/move-config

# remove the aws/onefs/node module by combining additional_nodes and bootstrap_nodes and
# move the remaining aws_instance resource to the aws/onefs module.
#
# GENERATED BY SCRIPT in codegen/


moved {
  from = module.bootstrap_nodes[0].aws_instance.onefs_node
  to   = aws_instance.onefs_node[0]
}


moved {
  from = module.additional_nodes[0].aws_instance.onefs_node
  to   = aws_instance.onefs_node[1]
}


moved {
  from = module.additional_nodes[1].aws_instance.onefs_node
  to   = aws_instance.onefs_node[2]
}


moved {
  from = module.additional_nodes[2].aws_instance.onefs_node
  to   = aws_instance.onefs_node[3]
}


moved {
  from = module.additional_nodes[3].aws_instance.onefs_node
  to   = aws_instance.onefs_node[4]
}


moved {
  from = module.additional_nodes[4].aws_instance.onefs_node
  to   = aws_instance.onefs_node[5]
}


moved {
  from = module.additional_nodes[5].aws_instance.onefs_node
  to   = aws_instance.onefs_node[6]
}


moved {
  from = module.additional_nodes[6].aws_instance.onefs_node
  to   = aws_instance.onefs_node[7]
}


moved {
  from = module.additional_nodes[7].aws_instance.onefs_node
  to   = aws_instance.onefs_node[8]
}


moved {
  from = module.additional_nodes[8].aws_instance.onefs_node
  to   = aws_instance.onefs_node[9]
}


moved {
  from = module.additional_nodes[9].aws_instance.onefs_node
  to   = aws_instance.onefs_node[10]
}


moved {
  from = module.additional_nodes[10].aws_instance.onefs_node
  to   = aws_instance.onefs_node[11]
}


moved {
  from = module.additional_nodes[11].aws_instance.onefs_node
  to   = aws_instance.onefs_node[12]
}


moved {
  from = module.additional_nodes[12].aws_instance.onefs_node
  to   = aws_instance.onefs_node[13]
}


moved {
  from = module.additional_nodes[13].aws_instance.onefs_node
  to   = aws_instance.onefs_node[14]
}


moved {
  from = module.additional_nodes[14].aws_instance.onefs_node
  to   = aws_instance.onefs_node[15]
}


moved {
  from = module.additional_nodes[15].aws_instance.onefs_node
  to   = aws_instance.onefs_node[16]
}


moved {
  from = module.additional_nodes[16].aws_instance.onefs_node
  to   = aws_instance.onefs_node[17]
}


moved {
  from = module.additional_nodes[17].aws_instance.onefs_node
  to   = aws_instance.onefs_node[18]
}


moved {
  from = module.additional_nodes[18].aws_instance.onefs_node
  to   = aws_instance.onefs_node[19]
}


moved {
  from = module.additional_nodes[19].aws_instance.onefs_node
  to   = aws_instance.onefs_node[20]
}


moved {
  from = module.additional_nodes[20].aws_instance.onefs_node
  to   = aws_instance.onefs_node[21]
}


moved {
  from = module.additional_nodes[21].aws_instance.onefs_node
  to   = aws_instance.onefs_node[22]
}


moved {
  from = module.additional_nodes[22].aws_instance.onefs_node
  to   = aws_instance.onefs_node[23]
}


moved {
  from = module.additional_nodes[23].aws_instance.onefs_node
  to   = aws_instance.onefs_node[24]
}


moved {
  from = module.additional_nodes[24].aws_instance.onefs_node
  to   = aws_instance.onefs_node[25]
}


moved {
  from = module.additional_nodes[25].aws_instance.onefs_node
  to   = aws_instance.onefs_node[26]
}


moved {
  from = module.additional_nodes[26].aws_instance.onefs_node
  to   = aws_instance.onefs_node[27]
}


moved {
  from = module.additional_nodes[27].aws_instance.onefs_node
  to   = aws_instance.onefs_node[28]
}


moved {
  from = module.additional_nodes[28].aws_instance.onefs_node
  to   = aws_instance.onefs_node[29]
}


moved {
  from = module.additional_nodes[29].aws_instance.onefs_node
  to   = aws_instance.onefs_node[30]
}


moved {
  from = module.additional_nodes[30].aws_instance.onefs_node
  to   = aws_instance.onefs_node[31]
}


moved {
  from = module.additional_nodes[31].aws_instance.onefs_node
  to   = aws_instance.onefs_node[32]
}


moved {
  from = module.additional_nodes[32].aws_instance.onefs_node
  to   = aws_instance.onefs_node[33]
}


moved {
  from = module.additional_nodes[33].aws_instance.onefs_node
  to   = aws_instance.onefs_node[34]
}


moved {
  from = module.additional_nodes[34].aws_instance.onefs_node
  to   = aws_instance.onefs_node[35]
}


moved {
  from = module.additional_nodes[35].aws_instance.onefs_node
  to   = aws_instance.onefs_node[36]
}


moved {
  from = module.additional_nodes[36].aws_instance.onefs_node
  to   = aws_instance.onefs_node[37]
}


moved {
  from = module.additional_nodes[37].aws_instance.onefs_node
  to   = aws_instance.onefs_node[38]
}


moved {
  from = module.additional_nodes[38].aws_instance.onefs_node
  to   = aws_instance.onefs_node[39]
}


moved {
  from = module.additional_nodes[39].aws_instance.onefs_node
  to   = aws_instance.onefs_node[40]
}


moved {
  from = module.additional_nodes[40].aws_instance.onefs_node
  to   = aws_instance.onefs_node[41]
}


moved {
  from = module.additional_nodes[41].aws_instance.onefs_node
  to   = aws_instance.onefs_node[42]
}


moved {
  from = module.additional_nodes[42].aws_instance.onefs_node
  to   = aws_instance.onefs_node[43]
}


moved {
  from = module.additional_nodes[43].aws_instance.onefs_node
  to   = aws_instance.onefs_node[44]
}


moved {
  from = module.additional_nodes[44].aws_instance.onefs_node
  to   = aws_instance.onefs_node[45]
}


moved {
  from = module.additional_nodes[45].aws_instance.onefs_node
  to   = aws_instance.onefs_node[46]
}


moved {
  from = module.additional_nodes[46].aws_instance.onefs_node
  to   = aws_instance.onefs_node[47]
}


moved {
  from = module.additional_nodes[47].aws_instance.onefs_node
  to   = aws_instance.onefs_node[48]
}


moved {
  from = module.additional_nodes[48].aws_instance.onefs_node
  to   = aws_instance.onefs_node[49]
}


moved {
  from = module.additional_nodes[49].aws_instance.onefs_node
  to   = aws_instance.onefs_node[50]
}


moved {
  from = module.additional_nodes[50].aws_instance.onefs_node
  to   = aws_instance.onefs_node[51]
}


moved {
  from = module.additional_nodes[51].aws_instance.onefs_node
  to   = aws_instance.onefs_node[52]
}


moved {
  from = module.additional_nodes[52].aws_instance.onefs_node
  to   = aws_instance.onefs_node[53]
}


moved {
  from = module.additional_nodes[53].aws_instance.onefs_node
  to   = aws_instance.onefs_node[54]
}


moved {
  from = module.additional_nodes[54].aws_instance.onefs_node
  to   = aws_instance.onefs_node[55]
}


moved {
  from = module.additional_nodes[55].aws_instance.onefs_node
  to   = aws_instance.onefs_node[56]
}


moved {
  from = module.additional_nodes[56].aws_instance.onefs_node
  to   = aws_instance.onefs_node[57]
}


moved {
  from = module.additional_nodes[57].aws_instance.onefs_node
  to   = aws_instance.onefs_node[58]
}


moved {
  from = module.additional_nodes[58].aws_instance.onefs_node
  to   = aws_instance.onefs_node[59]
}


moved {
  from = module.additional_nodes[59].aws_instance.onefs_node
  to   = aws_instance.onefs_node[60]
}


moved {
  from = module.additional_nodes[60].aws_instance.onefs_node
  to   = aws_instance.onefs_node[61]
}


moved {
  from = module.additional_nodes[61].aws_instance.onefs_node
  to   = aws_instance.onefs_node[62]
}


moved {
  from = module.additional_nodes[62].aws_instance.onefs_node
  to   = aws_instance.onefs_node[63]
}


moved {
  from = module.additional_nodes[63].aws_instance.onefs_node
  to   = aws_instance.onefs_node[64]
}


moved {
  from = module.additional_nodes[64].aws_instance.onefs_node
  to   = aws_instance.onefs_node[65]
}


moved {
  from = module.additional_nodes[65].aws_instance.onefs_node
  to   = aws_instance.onefs_node[66]
}


moved {
  from = module.additional_nodes[66].aws_instance.onefs_node
  to   = aws_instance.onefs_node[67]
}


moved {
  from = module.additional_nodes[67].aws_instance.onefs_node
  to   = aws_instance.onefs_node[68]
}


moved {
  from = module.additional_nodes[68].aws_instance.onefs_node
  to   = aws_instance.onefs_node[69]
}


moved {
  from = module.additional_nodes[69].aws_instance.onefs_node
  to   = aws_instance.onefs_node[70]
}


moved {
  from = module.additional_nodes[70].aws_instance.onefs_node
  to   = aws_instance.onefs_node[71]
}


moved {
  from = module.additional_nodes[71].aws_instance.onefs_node
  to   = aws_instance.onefs_node[72]
}


moved {
  from = module.additional_nodes[72].aws_instance.onefs_node
  to   = aws_instance.onefs_node[73]
}


moved {
  from = module.additional_nodes[73].aws_instance.onefs_node
  to   = aws_instance.onefs_node[74]
}


moved {
  from = module.additional_nodes[74].aws_instance.onefs_node
  to   = aws_instance.onefs_node[75]
}


moved {
  from = module.additional_nodes[75].aws_instance.onefs_node
  to   = aws_instance.onefs_node[76]
}


moved {
  from = module.additional_nodes[76].aws_instance.onefs_node
  to   = aws_instance.onefs_node[77]
}


moved {
  from = module.additional_nodes[77].aws_instance.onefs_node
  to   = aws_instance.onefs_node[78]
}


moved {
  from = module.additional_nodes[78].aws_instance.onefs_node
  to   = aws_instance.onefs_node[79]
}


moved {
  from = module.additional_nodes[79].aws_instance.onefs_node
  to   = aws_instance.onefs_node[80]
}


moved {
  from = module.additional_nodes[80].aws_instance.onefs_node
  to   = aws_instance.onefs_node[81]
}


moved {
  from = module.additional_nodes[81].aws_instance.onefs_node
  to   = aws_instance.onefs_node[82]
}


moved {
  from = module.additional_nodes[82].aws_instance.onefs_node
  to   = aws_instance.onefs_node[83]
}


moved {
  from = module.additional_nodes[83].aws_instance.onefs_node
  to   = aws_instance.onefs_node[84]
}


moved {
  from = module.additional_nodes[84].aws_instance.onefs_node
  to   = aws_instance.onefs_node[85]
}


moved {
  from = module.additional_nodes[85].aws_instance.onefs_node
  to   = aws_instance.onefs_node[86]
}


moved {
  from = module.additional_nodes[86].aws_instance.onefs_node
  to   = aws_instance.onefs_node[87]
}


moved {
  from = module.additional_nodes[87].aws_instance.onefs_node
  to   = aws_instance.onefs_node[88]
}


moved {
  from = module.additional_nodes[88].aws_instance.onefs_node
  to   = aws_instance.onefs_node[89]
}


moved {
  from = module.additional_nodes[89].aws_instance.onefs_node
  to   = aws_instance.onefs_node[90]
}


moved {
  from = module.additional_nodes[90].aws_instance.onefs_node
  to   = aws_instance.onefs_node[91]
}


moved {
  from = module.additional_nodes[91].aws_instance.onefs_node
  to   = aws_instance.onefs_node[92]
}


moved {
  from = module.additional_nodes[92].aws_instance.onefs_node
  to   = aws_instance.onefs_node[93]
}


moved {
  from = module.additional_nodes[93].aws_instance.onefs_node
  to   = aws_instance.onefs_node[94]
}


moved {
  from = module.additional_nodes[94].aws_instance.onefs_node
  to   = aws_instance.onefs_node[95]
}


moved {
  from = module.additional_nodes[95].aws_instance.onefs_node
  to   = aws_instance.onefs_node[96]
}


moved {
  from = module.additional_nodes[96].aws_instance.onefs_node
  to   = aws_instance.onefs_node[97]
}


moved {
  from = module.additional_nodes[97].aws_instance.onefs_node
  to   = aws_instance.onefs_node[98]
}


moved {
  from = module.additional_nodes[98].aws_instance.onefs_node
  to   = aws_instance.onefs_node[99]
}


moved {
  from = module.additional_nodes[99].aws_instance.onefs_node
  to   = aws_instance.onefs_node[100]
}

